### ISSUE TITLE
Ability to exclude path params / customize `MicrometerHttpFilter`

### ISSUE THREAD

**Issue by SHxKM** [MaksymDolgykh/dropwizard-micrometer#26]
Hi, 

Thanks for this awesome library. We have a case where we have routes per user:

```
user/{user-id}/favorites
user/{user-id}/playlists
user/{user-id}/...
```

Right now the library is generating stats per user, per endpoint, making our stats growth exponential and kinda problematic. Is there any built-in way to group this by the path parameter _before_ it is evaluated? so `user-id` `1,2,3,4...` are all under `user/{user-id}/favorites` route for example, instead of this being 4 different metrics.

Another useful thing may be the ability to manipulate values passed to `MicrometerHttpFilter`, which currently doesn't seem extensible/modifiable. I can simply copy the source code but that seems like a bad idea for maintainability.

**Comment by MaksymDolgykh** [comment]
@SHxKM  although it is possible to implement some configurable relabelling rules in the client lib, it is probably kind of anti pattern. It would be a duplication of what exists already and can be done on the prometheus server side with [metric_relabel_configs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs).

For your use case, something like the following in the prometheus server config could do the aggregation for `/user/{user-id}/favorites`

<pre>
metric_relabel_configs:
      - source_labels: [uri]
        target_label: uri
        regex: "/user/.+/favorites"
        action: replace
        replacement: "/user/{user-id}/favorites"
</pre>

It is just to give you an idea, probably you will need to adjust regex a bit.
Hope this helps.
Please let me know if you still see any reason for implementing some configurable rules in the lib.
